#!/bin/sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
SECRETS_FILE="$ROOT/.vercel-runtime-secrets"

if [ ! -f "$ROOT/.vercel/project.json" ]; then
  echo "Link the project with Vercel before provisioning environment variables." >&2
  exit 1
fi

if [ ! -s "$SECRETS_FILE" ]; then
  umask 077
  temporary="$SECRETS_FILE.tmp"
  cron_secret="$(openssl rand -hex 32)"
  {
    printf 'CRON_SECRET=%s\n' "$cron_secret"
  } > "$temporary"
  chmod 0600 "$temporary"
  mv "$temporary" "$SECRETS_FILE"
fi

# This file is generated by this script with hex-only values and mode 0600.
. "$SECRETS_FILE"

add_config() {
  printf '%s' "$2" | npx --yes vercel@latest env add "$1" production,preview,development --force --no-sensitive --yes
}

add_secret() {
  printf '%s' "$2" | npx --yes vercel@latest env add "$1" production,preview,development --force --sensitive --yes
}

add_secret CRON_SECRET "$CRON_SECRET"
add_config CLASSROOM_TIMEZONE "Asia/Ho_Chi_Minh"
add_config DB_POOL_SIZE "1"
add_config DB_MAX_OVERFLOW "1"
add_config DB_POOL_RECYCLE_SECONDS "300"
add_config HEARTBEAT_HISTORY_SECONDS "600"
add_config HEARTBEAT_RETENTION_DAYS "30"
add_config INTEGRITY_RETENTION_DAYS "30"
add_config RECEIPT_RETENTION_DAYS "35"

echo "Vercel environment configured. No web account or password is required."
